# Generated by Django 4.0.4 on 2022-05-30 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_image',
            new_name='image',
        ),
    ]
